version: '3'

services:
  mysql:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: YouDontWannaIt
      MYSQL_USER: sweeftUser
      MYSQL_PASSWORD: sweeftPassword
      MYSQL_DATABASE: sweeft_db